source 'git@github.com:Banuba/specs.git'
platform :ios, '11.0'
use_frameworks!

target 'Runner' do
  pod 'BanubaSDK', '0.0.13.2'
  pod 'BanubaVideoEditorSDK', '0.0.13.3'
  pod 'BanubaEffectPlayer', '0.0.10'
  pod 'BanubaAudioBrowserSDK', '0.0.13'
  pod 'BanubaMusicEditorSDK', '0.0.13.2'
  pod 'BanubaOverlayEditorSDK', '0.0.13.2'
  pod 'VideoEditor', '0.0.13.2'

end
